### ISSUE TITLE
Use `-F` instead of `-f` (follow, aka retry)

### ISSUE THREAD

**Issue by nhooey** [mapio/tmux-tail-f#2]
Use `-F` instead of `-f` so `tail` will continue tailing the file when the file is deleted and restored.

**Comment by mapio** [comment]
Want to patch and submit a pull request, or do you want me to do it?

**Comment by nhooey** [comment]
Wow, I made pull request #3 in the web page for the first time. GitHub is amazing.

**Comment by mapio** [comment]
:+1:
